import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Calculator, Check, ChevronRight, Copy, Percent, RotateCcw } from "lucide-react";
import { Layout } from "@/components/Layout";
import { SEO } from "@/components/SEO";

const canonical = "https://usonlinetools.com/yuzde-hesaplama";
const faqs = [
  ["Yüzde hesaplama nasıl yapılır?", "Bir sayının yüzdesini bulmak için sayı × yüzde ÷ 100 formülünü kullanın. Örneğin 500'ün %20'si 100'dür."],
  ["Bir sayının yüzde 20’si nasıl bulunur?", "Sayıyı 20 ile çarpıp 100’e bölün. 750 × 20 ÷ 100 = 150 sonucu elde edilir."],
  ["İki sayı arasındaki yüzde farkı nasıl hesaplanır?", "İki sayı arasındaki mutlak farkı sayıların ortalamasına bölüp 100 ile çarpın. Başlangıç değeri belliyse yüzde değişim formülü daha uygundur."],
  ["Yüzde artış nasıl hesaplanır?", "Yeni değerden eski değeri çıkarın, farkı eski değere bölün ve 100 ile çarpın: (yeni − eski) ÷ eski × 100."],
  ["Yüzde azalış nasıl hesaplanır?", "Eski değerden yeni değeri çıkarın, farkı eski değere bölün ve 100 ile çarpın: (eski − yeni) ÷ eski × 100."],
  ["İndirim yüzdesi nasıl hesaplanır?", "İndirim tutarını başlangıç fiyatına bölüp 100 ile çarpın. İndirimli fiyat için başlangıç fiyatından indirim tutarını çıkarın."],
  ["Zam oranı nasıl hesaplanır?", "Zam tutarını eski maaş veya fiyata bölüp 100 ile çarpın. Yeni tutar, eski tutar × (1 + zam oranı ÷ 100) şeklinde bulunur."],
  ["Yüzde puan ile yüzde değişim aynı şey mi?", "Hayır. %10’dan %15’e çıkmak 5 yüzde puanlık artıştır; göreli yüzde değişim ise %50’dir."],
  ["Bu yüzde hesaplayıcı ücretsiz mi?", "Evet. Yüzde hesaplama aracı ücretsizdir, kayıt gerektirmez ve telefon ile bilgisayarda çalışır."],
  ["İndirimli fiyattan eski fiyat bulunabilir mi?", "Evet. İndirimli fiyatı 1 − indirim oranı değerine bölün. 680 TL %20 indirimli fiyat ise 680 ÷ 0,80 = 850 TL'dir."],
];

function n(value: string) { const x = Number(value.replace(",", ".")); return Number.isFinite(x) ? x : null; }
function fmt(value: number | null, suffix = "") { return value === null ? "—" : `${value.toLocaleString("tr-TR", { maximumFractionDigits: 6 })}${suffix}`; }

export default function TurkishPercentageCalculator() {
  const [percent, setPercent] = useState("25");
  const [number, setNumber] = useState("8000");
  const [part, setPart] = useState("2000");
  const [whole, setWhole] = useState("8000");
  const [oldValue, setOldValue] = useState("8000");
  const [newValue, setNewValue] = useState("9000");
  const [amount, setAmount] = useState("850");
  const [rate, setRate] = useState("20");
  const [operation, setOperation] = useState<"discount" | "increase">("discount");
  const [salePrice, setSalePrice] = useState("680");
  const [discountRate, setDiscountRate] = useState("20");
  const [mode, setMode] = useState(0);
  const [copied, setCopied] = useState(false);
  const percentOf = useMemo(() => { const p = n(percent), x = n(number); return p === null || x === null ? null : p * x / 100; }, [percent, number]);
  const percentIs = useMemo(() => { const p = n(part), x = n(whole); return p === null || x === null || x === 0 ? null : p / x * 100; }, [part, whole]);
  const change = useMemo(() => { const a = n(oldValue), b = n(newValue); return a === null || b === null || a === 0 ? null : (b - a) / Math.abs(a) * 100; }, [oldValue, newValue]);
  const finalAmount = useMemo(() => { const a = n(amount), r = n(rate); return a === null || r === null ? null : a * (operation === "discount" ? 1 - r / 100 : 1 + r / 100); }, [amount, rate, operation]);
  const originalPrice = useMemo(() => { const a = n(salePrice), r = n(discountRate); return a === null || r === null || r >= 100 ? null : a / (1 - r / 100); }, [salePrice, discountRate]);
  useEffect(() => { const el = document.documentElement; const oldLang = el.lang, oldDir = el.dir; el.lang = "tr"; el.dir = "ltr"; return () => { el.lang = oldLang; el.dir = oldDir; }; }, []);
  const reset = () => { setPercent("25"); setNumber("8000"); setPart("30"); setWhole("200"); setOldValue("1000"); setNewValue("1250"); setAmount("850"); setRate("20"); setOperation("discount"); setSalePrice("680"); setDiscountRate("20"); setCopied(false); };
  const resultText = mode === 0 ? `${fmt(n(number))}'in %${fmt(n(percent))}'i ${fmt(percentOf)}'dir.` : mode === 1 ? `${fmt(n(part))}, ${fmt(n(whole))}'ün %${fmt(percentIs)}'idir.` : mode === 2 ? `${fmt(n(oldValue))}'den ${fmt(n(newValue))}'ye değişim %${fmt(change)} artıştır.` : mode === 3 ? `${fmt(n(oldValue))}'den ${fmt(n(newValue))}'ye değişim %${fmt(change)} azalıştır.` : mode === 4 ? `${fmt(n(amount))} TL'ye %${fmt(n(rate))} ${operation === "discount" ? "indirim" : "zam"} uygulanınca ${fmt(finalAmount)} TL olur.` : `${fmt(n(salePrice))} TL, %${fmt(n(discountRate))} indirimli ise eski fiyat ${fmt(originalPrice)} TL'dir.`;
  const copyResult = async () => { await navigator.clipboard?.writeText(resultText); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  const field = (label: string, value: string, set: (v: string) => void) => <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><input value={value} onChange={e => set(e.target.value)} inputMode="decimal" className="w-full rounded-lg border border-border bg-background px-4 py-3" /></label>;
  const box = (label: string, value: number | null, suffix = "") => <div className="rounded-lg border border-primary/20 bg-primary/10 p-4"><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black text-primary">{fmt(value, suffix)}</p></div>;
  return <Layout><SEO title="Yüzde Hesaplama – Online Yüzde Hesaplayıcı | US Online Tools" description="Bir sayının yüzdesini, yüzde artış ve azalışını, indirimli fiyatı veya iki sayı arasındaki yüzde oranını saniyeler içinde hesaplayın. Ücretsiz yüzde hesaplama aracı." canonical={canonical} schema={[{ "@type": "WebApplication", name: "Yüzde Hesaplama", url: canonical, applicationCategory: "CalculatorApplication", operatingSystem: "Any", description: "Ücretsiz Türkçe yüzde hesaplayıcı." }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana Sayfa", item: "https://usonlinetools.com/" }, { "@type": "ListItem", position: 2, name: "Yüzde Hesaplama", item: canonical }] }, { "@type": "FAQPage", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }]} />
    <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <nav className="mb-6 flex items-center gap-2 text-sm text-muted-foreground"><Link href="/">Ana Sayfa</Link><ChevronRight className="h-4 w-4" /><span>Yüzde Hesaplama</span></nav>
      <section className="mb-8 rounded-lg border border-primary/20 bg-gradient-to-br from-primary/10 via-card to-secondary/10 p-6 md:p-10"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary"><Percent className="h-4 w-4" /> TÜRKÇE HESAPLAYICI</div><h1 className="text-4xl font-black md:text-6xl">Yüzde Hesaplama</h1><p className="mt-5 max-w-3xl leading-8 text-muted-foreground">Yüzde hesaplayıcı ile bir sayının yüzdesini, bir sayının diğerine oranını, yüzde artışını, azalışını ve iki sayı arasındaki yüzde farkını anında bulun.</p></section>
      <section id="calculator" className="rounded-lg border border-border bg-card shadow-sm"><div className="border-b border-border px-5 py-4"><h2 className="text-xl font-black">Yüzde Hesaplayıcı</h2><p className="mt-1 text-sm text-muted-foreground">İşlem türünü seçin; sonuç ve formül otomatik güncellenir.</p></div><div className="space-y-6 p-5 md:p-6">
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["Bir Sayının Yüzdesi", "Bir Sayı Diğerinin Yüzde Kaçı?", "Yüzde Artış", "Yüzde Azalış", "İndirim / Zam Sonrası Tutar", "İndirimli Fiyattan Eski Fiyat"].map((label, i) => <button key={label} type="button" onClick={() => setMode(i)} className={`rounded-lg border px-3 py-3 text-left text-sm font-bold ${mode === i ? "border-primary bg-primary/10 text-primary" : "border-border hover:bg-muted"}`}>{label}</button>)}</div>
        <div className="rounded-lg border border-border bg-background p-5">{mode === 0 && <><h3 className="text-lg font-black">Bir sayının yüzdesi</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{field("Sayı", number, setNumber)}{field("Yüzde (%)", percent, setPercent)}{box("Sonuç", percentOf)}</div><p className="mt-4 text-sm text-muted-foreground">Formül: Sonuç = Sayı × (Yüzde ÷ 100)</p></>}{mode === 1 && <><h3 className="text-lg font-black">Bir sayı diğerinin yüzde kaçı?</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{field("Parça", part, setPart)}{field("Toplam", whole, setWhole)}{box("Sonuç", percentIs, "%")}</div><p className="mt-4 text-sm text-muted-foreground">Toplam değeri 0 olamaz. Formül: (Parça ÷ Toplam) × 100</p></>}{(mode === 2 || mode === 3) && <><h3 className="text-lg font-black">Yüzde {mode === 2 ? "artış" : "azalış"}</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{field("Eski Değer", oldValue, setOldValue)}{field("Yeni Değer", newValue, setNewValue)}{box("Sonuç", change, "%")}</div><p className="mt-4 text-sm text-muted-foreground">Formül: ((Yeni − Eski) ÷ Eski) × 100</p></>}{mode === 4 && <><h3 className="text-lg font-black">İndirim / zam sonrası tutar</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{field("Başlangıç Tutarı (TL)", amount, setAmount)}{field("Oran (%)", rate, setRate)}<label className="block"><span className="mb-2 block text-sm font-bold">İşlem</span><select value={operation} onChange={e => setOperation(e.target.value as "discount" | "increase")} className="w-full rounded-lg border border-border bg-background px-4 py-3"><option value="discount">İndirim</option><option value="increase">Zam</option></select></label></div>{box("Yeni Tutar", finalAmount, " TL")}</>}{mode === 5 && <><h3 className="text-lg font-black">İndirimli fiyattan eski fiyat</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{field("İndirimli Fiyat (TL)", salePrice, setSalePrice)}{field("İndirim Oranı (%)", discountRate, setDiscountRate)}{box("Eski Fiyat", originalPrice, " TL")}</div><p className="mt-4 text-sm text-muted-foreground">İndirim oranı %100'den küçük olmalıdır. Formül: İndirimli Fiyat ÷ (1 − Oran ÷ 100)</p></>}</div>
        <div className="rounded-lg border border-primary/20 bg-primary/5 p-4"><p className="font-bold">{resultText}</p><p className="mt-2 text-sm text-muted-foreground">Hesaplama türü: {["Bir sayının yüzdesi", "Bir sayı diğerinin yüzde kaçı", "Yüzde artış", "Yüzde azalış", "İndirim / zam sonrası tutar", "İndirimli fiyattan eski fiyat"][mode]}</p></div><div className="flex flex-wrap gap-3"><button type="button" onClick={copyResult} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />} {copied ? "Kopyalandı" : "Sonucu Kopyala"}</button><button type="button" onClick={reset} className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-bold hover:bg-muted"><RotateCcw className="h-4 w-4" /> Sıfırla</button></div>
      </div></section>
      <section className="mt-8 space-y-8">
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Yüzde Hesaplama Nedir?</h2><p className="mt-4 leading-8 text-muted-foreground">Yüzde hesaplama, bir değerin 100 eşit parçadaki oranını bulma işlemidir. Bu yüzde hesaplayıcı; bir sayının yüzdesini bulma, bir sayının diğerinin yüzde kaçı olduğunu öğrenme, yüzde artış ve azalışı karşılaştırma gibi günlük hesaplamaları tek yerde yapar. Sonuçlar değerleri girerken görünür ve Türkçe sayı biçimiyle gösterilir.</p><p className="mt-3 leading-8 text-muted-foreground">Yüzdeler alışverişte indirim ve zamları, işletmelerde komisyon ve kâr oranlarını, eğitimde başarı oranlarını, finansal planlamada değişimleri ve vergiye ilişkin yaklaşık hesaplamaları ifade etmek için kullanılır.</p></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Bu Yüzde Hesaplayıcı Nasıl Kullanılır?</h2><ol className="mt-4 list-decimal space-y-3 pl-6 leading-8 text-muted-foreground"><li>Bir sayının yüzdesini bulmak için “Yüzde (%)” ve “Sayı” alanlarını doldurun.</li><li>Bir değerin toplam içindeki oranını bulmak için parça ve toplam değerlerini yazın.</li><li>Değişimi ölçmek için eski ve yeni değerleri girin.</li><li>Sonucu kontrol edin; virgüllü ondalık değerler de kullanılabilir.</li><li>Yeni bir işlem için Sıfırla düğmesine basın.</li></ol></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Yüzde Nasıl Hesaplanır?</h2><p className="mt-4 leading-8 text-muted-foreground">Temel formül <strong>(sayı × yüzde) ÷ 100</strong> şeklindedir. Örneğin 500 × 20 ÷ 100 = 100; yani 500’ün %20’si 100’dür. Bir değerin toplam içindeki oranı için <strong>(parça ÷ toplam) × 100</strong> kullanılır. Hesaplamada toplamın sıfır olmaması gerekir.</p><h3 className="mt-5 text-lg font-black">Yüzde artış ve azalış</h3><p className="mt-2 leading-8 text-muted-foreground">Yüzde artışı bulmak için değişimi başlangıç değerine göre ölçün: (yeni − eski) ÷ eski × 100. Azalışta aynı mantıkla (eski − yeni) ÷ eski × 100 kullanılır. Başlangıç değeri sıfırsa göreli yüzde değişimi matematiksel olarak tanımsızdır.</p></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">İndirim ve Zam Hesaplama Örnekleri</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/50"><tr><th className="px-4 py-3">İşlem</th><th className="px-4 py-3">Formül</th><th className="px-4 py-3">Örnek</th><th className="px-4 py-3">Sonuç</th></tr></thead><tbody className="divide-y divide-border"><tr><td className="px-4 py-3 font-bold">Bir sayının yüzdesi</td><td className="px-4 py-3">Sayı × yüzde ÷ 100</td><td className="px-4 py-3">500 × 20 ÷ 100</td><td className="px-4 py-3">100</td></tr><tr><td className="px-4 py-3 font-bold">Yüzde artış</td><td className="px-4 py-3">Eski × (1 + yüzde/100)</td><td className="px-4 py-3">1.000 × 1,15</td><td className="px-4 py-3">1.150</td></tr><tr><td className="px-4 py-3 font-bold">Yüzde azalış</td><td className="px-4 py-3">Eski × (1 − yüzde/100)</td><td className="px-4 py-3">1.000 × 0,80</td><td className="px-4 py-3">800</td></tr><tr><td className="px-4 py-3 font-bold">İndirim</td><td className="px-4 py-3">Fiyat × (1 − indirim/100)</td><td className="px-4 py-3">2.000 × 0,75</td><td className="px-4 py-3">1.500</td></tr></tbody></table></div></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Yüzde Hesaplamanın Yaygın Kullanım Alanları</h2><ul className="mt-4 grid gap-2 list-disc pl-6 leading-8 text-muted-foreground sm:grid-cols-2"><li>İndirimli satış fiyatını kontrol etmek</li><li>Maaş zammı ve fiyat artışını bulmak</li><li>Komisyon, kâr veya büyüme oranını ölçmek</li><li>Not ve başarı yüzdesini hesaplamak</li><li>İki dönem arasındaki değişimi karşılaştırmak</li><li>Yaklaşık vergi veya KDV hesabı yapmak</li></ul></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Sık Yapılan Yüzde Hesaplama Hataları</h2><p className="mt-4 leading-8 text-muted-foreground">İndirimden sonra aynı oranda zam yapılınca başlangıç fiyatına dönüleceği varsayımı sık görülür; ancak %20 indirim ve ardından %20 zam aynı taban üzerinden hesaplanmadığı için sonuç farklı olur. Ayrıca yüzde puan ile yüzde değişimi karıştırmayın: %20’den %30’a çıkış 10 yüzde puanı, göreli olarak ise %50 artıştır. Yüzde değişim hesabında doğru başlangıç değerini seçmek ve sıfıra bölme durumunu kontrol etmek de önemlidir.</p></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">İlgili Araçlar</h2><p className="mt-3 leading-8 text-muted-foreground">Daha özel hesaplamalar için <Link href="/kdv-hesaplama" className="font-bold text-primary hover:underline">KDV Hesaplama</Link> ve <Link href="/kidem-tazminati-hesaplama" className="font-bold text-primary hover:underline">Kıdem Tazminatı Hesaplama</Link> araçlarına göz atın.</p></article>
        <article className="rounded-lg border border-border bg-card p-6"><h2 className="text-2xl font-black">Sık Sorulan Sorular</h2><div className="mt-5 space-y-5">{faqs.map(([q, a]) => <div key={q}><h3 className="font-black">{q}</h3><p className="mt-1 leading-8 text-muted-foreground">{a}</p></div>)}</div></article>
        <article className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-6"><h2 className="text-2xl font-black">Bilgilendirme</h2><p className="mt-4 leading-8 text-muted-foreground">Bu araç yalnızca bilgilendirme amaçlıdır. Vergi, maaş, resmi beyan veya sözleşme gibi işlemlerde kesin sonuç için ilgili resmi kaynakları veya uzmanları esas alın.</p></article>
      </section>
      <p className="mt-8 text-sm text-muted-foreground"><Calculator className="mr-1 inline h-4 w-4" /> İndirim, zam, KDV ve oran hesaplamalarında kullanabilirsiniz.</p>
    </main></Layout>;
}
