import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Copy, Download, Globe, Link2, Shield } from "lucide-react";
import UtilityToolPageShell from "./UtilityToolPageShell";

type MatchMode = "exact" | "prefix";
type RedirectCode = 301 | 302;

function extractPath(input: string) {
  const trimmed = input.trim();
  if (!trimmed) return "/";

  try {
    const parsed = new URL(trimmed);
    return parsed.pathname || "/";
  } catch {
    if (trimmed.startsWith("/")) return trimmed;
    return `/${trimmed.replace(/^\/+/, "")}`;
  }
}

function extractDomain(input: string) {
  const trimmed = input.trim();
  if (!trimmed) return "";

  try {
    const parsed = new URL(trimmed.includes("://") ? trimmed : `https://${trimmed}`);
    return parsed.hostname.replace(/^www\./, "");
  } catch {
    return trimmed.replace(/^https?:\/\//, "").replace(/^www\./, "").split("/")[0];
  }
}

function escapeRegex(input: string) {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildRedirectRule({
  sourcePath,
  destination,
  sourceDomain,
  matchMode,
  redirectCode,
  keepQuery,
  appendRemainder,
}: {
  sourcePath: string;
  destination: string;
  sourceDomain: string;
  matchMode: MatchMode;
  redirectCode: RedirectCode;
  keepQuery: boolean;
  appendRemainder: boolean;
}) {
  const normalizedPath = extractPath(sourcePath);
  const normalizedDomain = extractDomain(sourceDomain);
  const pathWithoutSlash = normalizedPath.replace(/^\/+/, "").replace(/\/+$/, "");
  const safeDestination = destination.trim();
  const pattern =
    matchMode === "exact"
      ? pathWithoutSlash
        ? `^${escapeRegex(pathWithoutSlash)}/?$`
        : "^$"
      : pathWithoutSlash
        ? `^${escapeRegex(pathWithoutSlash)}(?:/(.*))?/?$`
        : "^(.*)$";
  const destinationWithTail =
    matchMode === "prefix" && appendRemainder
      ? `${safeDestination.replace(/\/+$/, "")}/$1`
      : safeDestination;
  const flags = [`R=${redirectCode}`, "L", keepQuery ? "QSA" : ""].filter(Boolean).join(",");
  const lines = ["RewriteEngine On"];

  if (normalizedDomain) {
    lines.push(`RewriteCond %{HTTP_HOST} ^(?:www\\.)?${escapeRegex(normalizedDomain)}$ [NC]`);
  }

  lines.push(`RewriteRule ${pattern} ${destinationWithTail} [${flags}]`);

  const simpleDirective =
    matchMode === "exact" && !normalizedDomain
      ? `Redirect ${redirectCode} ${normalizedPath} ${safeDestination}`
      : "";

  return {
    normalizedPath,
    normalizedDomain,
    rewriteBlock: lines.join("\n"),
    simpleDirective,
    destinationWithTail,
  };
}

export default function HtaccessRedirectGenerator() {
  const [redirectCode, setRedirectCode] = useState<RedirectCode>(301);
  const [matchMode, setMatchMode] = useState<MatchMode>("exact");
  const [sourcePath, setSourcePath] = useState("/old-pricing");
  const [destination, setDestination] = useState("https://example.com/pricing");
  const [sourceDomain, setSourceDomain] = useState("");
  const [keepQuery, setKeepQuery] = useState(true);
  const [appendRemainder, setAppendRemainder] = useState(true);
  const [copied, setCopied] = useState("");
  const [downloaded, setDownloaded] = useState(false);

  const output = useMemo(
    () =>
      buildRedirectRule({
        sourcePath,
        destination,
        sourceDomain,
        matchMode,
        redirectCode,
        keepQuery,
        appendRemainder,
      }),
    [appendRemainder, destination, keepQuery, matchMode, redirectCode, sourceDomain, sourcePath],
  );

  const destinationWarning = !destination.trim()
    ? "Add a destination URL or path to generate a valid redirect."
    : destination.trim().startsWith("http://") || destination.trim().startsWith("https://") || destination.trim().startsWith("/")
      ? ""
      : "Destination usually works best as an absolute URL or a slash-prefixed path.";

  const htaccessFileContent = useMemo(
    () =>
      [
        "# .htaccess redirect block generated by US Online Tools",
        `# Redirect code: ${redirectCode}`,
        `# Match mode: ${matchMode}`,
        `# Source path: ${output.normalizedPath}`,
        `# Source domain: ${output.normalizedDomain || "current host"}`,
        "",
        output.rewriteBlock,
      ].join("\n"),
    [matchMode, output.normalizedDomain, output.normalizedPath, output.rewriteBlock, redirectCode],
  );

  const copyValue = async (label: string, value: string) => {
    await navigator.clipboard.writeText(value);
    setCopied(label);
    window.setTimeout(() => setCopied(""), 1800);
  };

  const downloadHtaccess = () => {
    const blob = new Blob([htaccessFileContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = ".htaccess";
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    setDownloaded(true);
    window.setTimeout(() => setDownloaded(false), 1800);
  };

  const calculator = (
    <div className="space-y-6">
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => {
            setRedirectCode(301);
            setMatchMode("exact");
            setSourcePath("/old-pricing");
            setDestination("https://example.com/pricing");
            setSourceDomain("");
            setKeepQuery(true);
            setAppendRemainder(true);
          }}
          className="rounded-xl border border-border bg-card px-4 py-2.5 text-sm font-semibold text-foreground hover:border-blue-500/40 hover:bg-muted transition-colors"
        >
          Page Migration Preset
        </button>
        <button
          onClick={() => {
            setRedirectCode(301);
            setMatchMode("prefix");
            setSourcePath("/blog");
            setDestination("https://example.com/resources");
            setSourceDomain("old.example.com");
            setKeepQuery(true);
            setAppendRemainder(true);
          }}
          className="rounded-xl border border-border bg-card px-4 py-2.5 text-sm font-semibold text-foreground hover:border-blue-500/40 hover:bg-muted transition-colors"
        >
          Section Move Preset
        </button>
        <button
          onClick={() => {
            setRedirectCode(302);
            setMatchMode("exact");
            setSourcePath("/spring-sale");
            setDestination("https://example.com/landing/spring-sale");
            setSourceDomain("");
            setKeepQuery(false);
            setAppendRemainder(false);
          }}
          className="rounded-xl border border-border bg-card px-4 py-2.5 text-sm font-semibold text-foreground hover:border-blue-500/40 hover:bg-muted transition-colors"
        >
          Temporary Redirect Preset
        </button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[1.4fr_0.9fr] gap-5">
        <div className="space-y-5">
          <div className="rounded-2xl border border-blue-500/20 bg-blue-500/5 p-5 shadow-sm">
            <div className="mb-4 flex items-center justify-between gap-3">
              <div>
                <p className="text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground">Redirect Controls</p>
                <p className="text-sm text-muted-foreground">Generate Apache redirect rules for one-off page moves or section-level migrations.</p>
              </div>
              <Link2 className="h-5 w-5 text-blue-500" />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="mb-2 block text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">Redirect Type</label>
                <select value={String(redirectCode)} onChange={(event) => setRedirectCode(Number(event.target.value) as RedirectCode)} className="tool-calc-input w-full">
                  <option value="301">301 Permanent</option>
                  <option value="302">302 Temporary</option>
                </select>
              </div>

              <div>
                <label className="mb-2 block text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">Match Mode</label>
                <select value={matchMode} onChange={(event) => setMatchMode(event.target.value as MatchMode)} className="tool-calc-input w-full">
                  <option value="exact">Exact Path</option>
                  <option value="prefix">Path Prefix</option>
                </select>
              </div>

              <div>
                <label className="mb-2 block text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">Source Path</label>
                <input value={sourcePath} onChange={(event) => setSourcePath(event.target.value)} spellCheck={false} className="tool-calc-input w-full font-mono" placeholder="/old-page" />
              </div>

              <div>
                <label className="mb-2 block text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">Destination URL</label>
                <input value={destination} onChange={(event) => setDestination(event.target.value)} spellCheck={false} className="tool-calc-input w-full font-mono" placeholder="https://example.com/new-page" />
              </div>

              <div className="sm:col-span-2">
                <label className="mb-2 block text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">Optional Source Domain</label>
                <input value={sourceDomain} onChange={(event) => setSourceDomain(event.target.value)} spellCheck={false} className="tool-calc-input w-full font-mono" placeholder="old.example.com" />
                <p className="mt-2 text-xs text-muted-foreground">Leave the domain blank if the rule will live inside the same site and should not restrict by host.</p>
              </div>
            </div>

            <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">
              <label className="flex items-start gap-3 rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">
                <input type="checkbox" checked={keepQuery} onChange={(event) => setKeepQuery(event.target.checked)} className="mt-0.5" />
                <span>
                  <span className="block font-bold text-foreground">Preserve query string</span>
                  <span className="block mt-1">Adds the `QSA` flag so original tracking or filter parameters are carried through.</span>
                </span>
              </label>

              <label className={`flex items-start gap-3 rounded-xl border bg-card p-4 text-sm ${matchMode === "prefix" ? "border-border text-muted-foreground" : "border-border/60 text-muted-foreground/60"}`}>
                <input type="checkbox" checked={appendRemainder} disabled={matchMode !== "prefix"} onChange={(event) => setAppendRemainder(event.target.checked)} className="mt-0.5" />
                <span>
                  <span className="block font-bold text-foreground">Append remaining path</span>
                  <span className="block mt-1">Useful for section moves like `/blog/post-a` to `/resources/post-a`. Enabled only for prefix matches.</span>
                </span>
              </label>
            </div>

            {destinationWarning ? <p className="mt-4 text-sm text-amber-600">{destinationWarning}</p> : null}

            <div className="mt-4 grid grid-cols-2 lg:grid-cols-4 gap-3">
              <div className="rounded-xl border border-border bg-card p-4">
                <p className="text-[10px] font-black uppercase tracking-[0.18em] text-muted-foreground">Path Mode</p>
                <p className="mt-2 text-2xl font-black text-foreground">{matchMode === "exact" ? "Exact" : "Prefix"}</p>
              </div>
              <div className="rounded-xl border border-border bg-card p-4">
                <p className="text-[10px] font-black uppercase tracking-[0.18em] text-muted-foreground">Status Code</p>
                <p className="mt-2 text-2xl font-black text-foreground">{redirectCode}</p>
              </div>
              <div className="rounded-xl border border-border bg-card p-4">
                <p className="text-[10px] font-black uppercase tracking-[0.18em] text-muted-foreground">Host Condition</p>
                <p className="mt-2 text-2xl font-black text-foreground">{output.normalizedDomain ? "Yes" : "No"}</p>
              </div>
              <div className="rounded-xl border border-border bg-card p-4">
                <p className="text-[10px] font-black uppercase tracking-[0.18em] text-muted-foreground">Query Handling</p>
                <p className="mt-2 text-2xl font-black text-foreground">{keepQuery ? "Keep" : "Drop"}</p>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-blue-500/20 bg-blue-500/5 p-5">
            <div className="mb-4 flex items-center justify-between gap-3">
              <div>
                <p className="text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground">Generated Rewrite Block</p>
                <p className="text-sm text-muted-foreground">Use this version when you need domain conditions or prefix matching.</p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={downloadHtaccess}
                  className={`inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold transition-colors ${
                    downloaded ? "bg-emerald-500 text-white" : "border border-border bg-background text-foreground hover:bg-muted"
                  }`}
                >
                  <Download className="h-3.5 w-3.5" />
                  {downloaded ? "Downloaded" : "Download"}
                </button>
                <button
                  type="button"
                  onClick={() => copyValue("rewrite", output.rewriteBlock)}
                  className="inline-flex items-center gap-1 rounded-lg border border-border bg-background px-3 py-2 text-xs font-bold text-foreground hover:bg-muted"
                >
                  <Copy className="h-3.5 w-3.5" />
                  {copied === "rewrite" ? "Copied" : "Copy"}
                </button>
              </div>
            </div>
            <textarea readOnly value={output.rewriteBlock} spellCheck={false} className="min-h-[170px] w-full resize-y rounded-2xl border border-border bg-slate-950 p-4 font-mono text-sm leading-relaxed text-slate-100 outline-none" />
          </div>

          <div className="rounded-2xl border border-border bg-card p-5">
            <div className="mb-4 flex items-center justify-between gap-3">
              <div>
                <p className="text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground">Simple Redirect Alternative</p>
                <p className="text-sm text-muted-foreground">Available only for same-domain exact redirects where Apache's short `Redirect` directive is enough.</p>
              </div>
              <button onClick={() => copyValue("simple", output.simpleDirective)} disabled={!output.simpleDirective} className="inline-flex items-center gap-1 rounded-lg border border-border bg-background px-3 py-2 text-xs font-bold text-foreground hover:bg-muted disabled:opacity-50">
                <Copy className="h-3.5 w-3.5" />
                {copied === "simple" ? "Copied" : "Copy"}
              </button>
            </div>
            <textarea readOnly value={output.simpleDirective || "Switch to an exact path match with no source-domain restriction to enable the shorter Redirect directive."} spellCheck={false} className="min-h-[120px] w-full resize-y rounded-2xl border border-border bg-slate-950 p-4 font-mono text-sm leading-relaxed text-slate-100 outline-none" />
          </div>
        </div>

        <div className="space-y-5">
          <div className="rounded-2xl border border-border bg-card p-5">
            <p className="mb-4 text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground">Deployment Reading</p>
            <div className="space-y-3 text-sm text-muted-foreground">
              <div className="rounded-xl border border-border bg-muted/40 p-4">
                <p className="font-bold text-foreground">Normalized Source Path</p>
                <p className="mt-1 font-mono text-xs">{output.normalizedPath}</p>
              </div>
              <div className="rounded-xl border border-border bg-muted/40 p-4">
                <p className="font-bold text-foreground">Destination Used</p>
                <p className="mt-1 break-all font-mono text-xs">{output.destinationWithTail}</p>
              </div>
              <div className="rounded-xl border border-border bg-muted/40 p-4">
                <p className="font-bold text-foreground">Trailing Slash Behavior</p>
                <p className="mt-1">The generated regex allows an optional trailing slash, which helps catch both `/page` and `/page/` with one rule.</p>
              </div>
              <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4">
                <p className="font-bold text-foreground">Order Matters</p>
                <p className="mt-1">Put specific redirects above broader section redirects in `.htaccess` so a general prefix rule does not capture a path that should go somewhere else.</p>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-border bg-card p-5">
            <p className="mb-4 text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground">Copy-Ready Notes</p>
            {[
              {
                label: "Migration summary",
                value: `Code: ${redirectCode}\nMode: ${matchMode}\nSource path: ${output.normalizedPath}\nSource domain: ${output.normalizedDomain || "Current site"}\nDestination: ${output.destinationWithTail}\nKeep query: ${keepQuery ? "Yes" : "No"}`,
              },
              {
                label: "Paste with comment",
                value: `# Redirect generated for ${output.normalizedPath}\n${output.rewriteBlock}`,
              },
            ].map((item) => (
              <div key={item.label} className="mb-3 rounded-xl border border-border bg-muted/40 p-3 last:mb-0">
                <div className="flex items-center justify-between gap-3">
                  <p className="text-[11px] font-black uppercase tracking-[0.18em] text-muted-foreground">{item.label}</p>
                  <button onClick={() => copyValue(item.label, item.value)} className="text-xs font-bold text-blue-600">
                    {copied === item.label ? "Copied" : "Copy"}
                  </button>
                </div>
                <pre className="mt-2 overflow-x-auto rounded-xl bg-slate-950 p-3 text-xs leading-relaxed text-slate-100"><code>{item.value}</code></pre>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <UtilityToolPageShell
      title=".htaccess Redirect Generator"
      seoTitle=".htaccess Redirect Generator - Create Apache 301 and 302 Rules"
      seoDescription="Free .htaccess redirect generator. Create Apache RewriteRule and Redirect directives for 301 and 302 redirects with domain, path, and query controls."
      canonical="https://usonlinetools.com/seo/htaccess-redirect-generator"
      categoryName="SEO Tools"
      categoryHref="/category/seo"
      heroDescription="Generate Apache `.htaccess` redirect rules for URL migrations, deleted pages, and section moves. Configure the status code, path matching behavior, optional source domain, and query handling, then copy a ready-to-paste rule."
      heroIcon={<Link2 className="h-3.5 w-3.5" />}
      calculatorLabel="Apache Redirect Builder"
      calculatorDescription="Build exact or prefix redirects, add host conditions when needed, and copy either a full RewriteRule block or a simple Redirect directive."
      calculator={calculator}
      howSteps={[
        { title: "Choose whether the redirect is permanent or temporary", description: "Use 301 when the move should be treated as the new canonical location long term. Use 302 when the redirect is temporary and the original URL may return later." },
        { title: "Enter the source path and destination URL", description: "Paste the old page path or section path and the destination users should land on. Add a source domain only when the rule must be limited to one hostname." },
        { title: "Pick exact or prefix matching based on the migration scope", description: "Exact matches are for one page. Prefix matches are for section moves like `/blog/...` to `/resources/...` where multiple URLs should follow one pattern." },
        { title: "Copy the generated block into `.htaccess` and place it carefully", description: "Put more specific rules above broader ones so section redirects do not swallow single-page redirects that need different targets." },
      ]}
      interpretationCards={[
        { title: "301 passes long-term intent", description: "A 301 redirect tells browsers and search engines that the move is intended to be permanent.", className: "bg-emerald-500/5 border-emerald-500/20" },
        { title: "302 is safer for temporary campaigns", description: "Use 302 when the redirect is short-lived and you do not want the old URL treated as permanently replaced.", className: "bg-amber-500/5 border-amber-500/20" },
        { title: "Prefix mode can move entire folders", description: "When you enable prefix matching, one rule can catch whole path sections such as `/blog/post-a` and `/blog/post-b`.", className: "bg-blue-500/5 border-blue-500/20" },
        { title: "Domain conditions narrow the rule scope", description: "Adding a source domain is useful during hostname migrations or multisite Apache setups where the rule should not run everywhere.", className: "bg-cyan-500/5 border-cyan-500/20" },
      ]}
      examples={[
        { scenario: "Single page rename", input: "/old-pricing -> https://example.com/pricing", output: "301 exact redirect for one retired URL" },
        { scenario: "Blog section migration", input: "/blog/* -> https://example.com/resources/*", output: "Prefix redirect that appends the remaining path" },
        { scenario: "Temporary landing page switch", input: "/spring-sale -> new campaign URL", output: "302 redirect without long-term migration intent" },
        { scenario: "Hostname cleanup", input: "old.example.com + /docs -> new docs location", output: "Rewrite block with a host condition in `.htaccess`" },
      ]}
      whyChoosePoints={[
        "This page generates real Apache redirect syntax instead of placeholder SEO copy.",
        "It handles both exact path redirects and broader section moves in the same workflow.",
        "The domain field supports hostname-specific rules without forcing that complexity for every redirect.",
        "Simple Redirect output is included when the short directive is enough, while RewriteRule output covers more advanced cases.",
        "The page follows the same long-form structure as the site's flagship calculator pages while keeping the live rule generator above the fold.",
      ]}
      faqs={[
        { q: "Should I use 301 or 302?", a: "Use 301 for permanent moves and 302 for temporary redirects. If the old URL is truly being replaced, 301 is usually the right choice." },
        { q: "When should I use exact match instead of prefix match?", a: "Use exact match for one URL. Use prefix match when multiple URLs share the same starting path and should all be redirected with one rule." },
        { q: "What does the optional source domain do?", a: "It adds a RewriteCond for the host so the redirect only runs on that domain or subdomain." },
        { q: "Why does the generator allow an optional trailing slash?", a: "It helps one rule catch both slash and non-slash variants of the same path, which is common during migrations." },
        { q: "What does QSA mean?", a: "QSA stands for Query String Append. It preserves incoming query parameters and passes them through to the destination." },
        { q: "Can I use the short Redirect directive for everything?", a: "No. The short directive is useful for simple exact redirects on the current site, but host conditions and broader pattern moves usually need mod_rewrite syntax." },
        { q: "Where should I place these rules in `.htaccess`?", a: "Put specific rules above broad ones, and keep redirect blocks in a predictable section so future migration work is easier to manage." },
        { q: "Does this page validate my live server config?", a: "No. It generates the rule text, but you still need to test it on your Apache environment after pasting it into `.htaccess`." },
      ]}
      relatedTools={[
        { title: "Canonical Tag Generator", slug: "canonical-tag-generator", icon: <Globe className="h-4 w-4" />, color: 210, benefit: "Pair redirects with clear canonical signals during migrations" },
        { title: "Robots.txt Generator", slug: "robots-txt-generator", icon: <Shield className="h-4 w-4" />, color: 145, benefit: "Manage crawl access while restructuring sections" },
        { title: "XML Sitemap Generator", slug: "sitemap-generator", icon: <ArrowRight className="h-4 w-4" />, color: 30, benefit: "Publish updated destination URLs after redirects go live" },
        { title: "Meta Tag Generator", slug: "meta-tag-generator", icon: <Link2 className="h-4 w-4" />, color: 280, benefit: "Refresh page metadata once the new URLs are in place" },
        { title: "Open Graph Generator", slug: "open-graph-generator", icon: <CheckCircle2 className="h-4 w-4" />, color: 90, benefit: "Update shared-link cards for migrated landing pages" },
        { title: "Readability Checker", slug: "readability-checker", icon: <Copy className="h-4 w-4" />, color: 15, benefit: "Review revised destination page content after the move" },
      ]}
      ctaTitle="Need Another SEO Utility?"
      ctaDescription="Keep replacing placeholder SEO routes with working generators and validators that are ready to copy into production workflows."
      ctaHref="/category/seo"
    />
  );
}
